version: '3'

# Define services
services:

  # MySQL Service
  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - container-volume:/var/lib/mysql
      - ./mysql/mysqldump.sql:/docker-entrypoint-initdb.d/mysqldump.sql
    environment:
      MYSQL_ROOT_PASSWORD: FgTQTzNM62cC63K
      MYSQL_DATABASE: learninghub
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
    cap_add:
      - SYS_NICE
    
  # Redis Service
  redis:
    image: "redis:alpine" 
    container_name: redis
    restart: always
    volumes:
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports: 
        - "6379:6379"
    networks:
        - backend

volumes:
  container-volume:

networks:
  backend: